/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConcluirRouteImport } from './routes/auth.concluir'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedRelatoriosOsRouteImport } from './routes/_authenticated/relatorios-os'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReconciliacaoRouteImport } from './routes/_authenticated/reconciliacao'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedOrdensServicoRouteImport } from './routes/_authenticated/ordens-servico'
import { Route as AuthenticatedLicencasRouteImport } from './routes/_authenticated/licencas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCentrosCustoRouteImport } from './routes/_authenticated/centros-custo'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAtivosRouteImport } from './routes/_authenticated/ativos'
import { Route as AuthenticatedAlocacoesRouteImport } from './routes/_authenticated/alocacoes'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as Authenticated403RouteImport } from './routes/_authenticated/403'
import { Route as AuthenticatedServicosIdRouteImport } from './routes/_authenticated/servicos_.$id'
import { Route as AuthenticatedOrdensServicoIdRouteImport } from './routes/_authenticated/ordens-servico_.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes_.$id'
import { Route as AuthenticatedAtivosIdRouteImport } from './routes/_authenticated/ativos_.$id'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAuditoriaTabelaIdRouteImport } from './routes/_authenticated/auditoria_.$tabela.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConcluirRoute = AuthConcluirRouteImport.update({
  id: '/concluir',
  path: '/concluir',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosOsRoute =
  AuthenticatedRelatoriosOsRouteImport.update({
    id: '/relatorios-os',
    path: '/relatorios-os',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReconciliacaoRoute =
  AuthenticatedReconciliacaoRouteImport.update({
    id: '/reconciliacao',
    path: '/reconciliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdensServicoRoute =
  AuthenticatedOrdensServicoRouteImport.update({
    id: '/ordens-servico',
    path: '/ordens-servico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLicencasRoute = AuthenticatedLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCentrosCustoRoute =
  AuthenticatedCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosRoute = AuthenticatedAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlocacoesRoute = AuthenticatedAlocacoesRouteImport.update({
  id: '/alocacoes',
  path: '/alocacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Authenticated403Route = Authenticated403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosIdRoute = AuthenticatedServicosIdRouteImport.update({
  id: '/servicos_/$id',
  path: '/servicos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdensServicoIdRoute =
  AuthenticatedOrdensServicoIdRouteImport.update({
    id: '/ordens-servico_/$id',
    path: '/ordens-servico/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosIdRoute = AuthenticatedAtivosIdRouteImport.update({
  id: '/ativos_/$id',
  path: '/ativos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditoriaTabelaIdRoute =
  AuthenticatedAuditoriaTabelaIdRouteImport.update({
    id: '/auditoria_/$tabela/$id',
    path: '/auditoria/$tabela/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/403': typeof Authenticated403Route
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/alocacoes': typeof AuthenticatedAlocacoesRoute
  '/ativos': typeof AuthenticatedAtivosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-os': typeof AuthenticatedRelatoriosOsRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/concluir': typeof AuthConcluirRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/ordens-servico/$id': typeof AuthenticatedOrdensServicoIdRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/auditoria/$tabela/$id': typeof AuthenticatedAuditoriaTabelaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/403': typeof Authenticated403Route
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/alocacoes': typeof AuthenticatedAlocacoesRoute
  '/ativos': typeof AuthenticatedAtivosRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-os': typeof AuthenticatedRelatoriosOsRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/concluir': typeof AuthConcluirRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/ordens-servico/$id': typeof AuthenticatedOrdensServicoIdRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/auditoria/$tabela/$id': typeof AuthenticatedAuditoriaTabelaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/_authenticated/403': typeof Authenticated403Route
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/alocacoes': typeof AuthenticatedAlocacoesRoute
  '/_authenticated/ativos': typeof AuthenticatedAtivosRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/licencas': typeof AuthenticatedLicencasRoute
  '/_authenticated/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/relatorios-os': typeof AuthenticatedRelatoriosOsRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/concluir': typeof AuthConcluirRoute
  '/_authenticated/ativos_/$id': typeof AuthenticatedAtivosIdRoute
  '/_authenticated/clientes_/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/ordens-servico_/$id': typeof AuthenticatedOrdensServicoIdRoute
  '/_authenticated/servicos_/$id': typeof AuthenticatedServicosIdRoute
  '/_authenticated/auditoria_/$tabela/$id': typeof AuthenticatedAuditoriaTabelaIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/privacidade'
    | '/register'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/403'
    | '/acessos'
    | '/alertas'
    | '/alocacoes'
    | '/ativos'
    | '/auditoria'
    | '/centros-custo'
    | '/clientes'
    | '/colaboradores'
    | '/contratos'
    | '/dashboard'
    | '/estoque'
    | '/licencas'
    | '/ordens-servico'
    | '/pecas'
    | '/produtos'
    | '/reconciliacao'
    | '/relatorios'
    | '/relatorios-os'
    | '/servicos'
    | '/solicitacoes'
    | '/unidades'
    | '/auth/callback'
    | '/auth/concluir'
    | '/ativos/$id'
    | '/clientes/$id'
    | '/ordens-servico/$id'
    | '/servicos/$id'
    | '/auditoria/$tabela/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/privacidade'
    | '/register'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/403'
    | '/acessos'
    | '/alertas'
    | '/alocacoes'
    | '/ativos'
    | '/auditoria'
    | '/centros-custo'
    | '/clientes'
    | '/colaboradores'
    | '/contratos'
    | '/dashboard'
    | '/estoque'
    | '/licencas'
    | '/ordens-servico'
    | '/pecas'
    | '/produtos'
    | '/reconciliacao'
    | '/relatorios'
    | '/relatorios-os'
    | '/servicos'
    | '/solicitacoes'
    | '/unidades'
    | '/auth/callback'
    | '/auth/concluir'
    | '/ativos/$id'
    | '/clientes/$id'
    | '/ordens-servico/$id'
    | '/servicos/$id'
    | '/auditoria/$tabela/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/privacidade'
    | '/register'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/_authenticated/403'
    | '/_authenticated/acessos'
    | '/_authenticated/alertas'
    | '/_authenticated/alocacoes'
    | '/_authenticated/ativos'
    | '/_authenticated/auditoria'
    | '/_authenticated/centros-custo'
    | '/_authenticated/clientes'
    | '/_authenticated/colaboradores'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/licencas'
    | '/_authenticated/ordens-servico'
    | '/_authenticated/pecas'
    | '/_authenticated/produtos'
    | '/_authenticated/reconciliacao'
    | '/_authenticated/relatorios'
    | '/_authenticated/relatorios-os'
    | '/_authenticated/servicos'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/unidades'
    | '/auth/callback'
    | '/auth/concluir'
    | '/_authenticated/ativos_/$id'
    | '/_authenticated/clientes_/$id'
    | '/_authenticated/ordens-servico_/$id'
    | '/_authenticated/servicos_/$id'
    | '/_authenticated/auditoria_/$tabela/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/concluir': {
      id: '/auth/concluir'
      path: '/concluir'
      fullPath: '/auth/concluir'
      preLoaderRoute: typeof AuthConcluirRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-os': {
      id: '/_authenticated/relatorios-os'
      path: '/relatorios-os'
      fullPath: '/relatorios-os'
      preLoaderRoute: typeof AuthenticatedRelatoriosOsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reconciliacao': {
      id: '/_authenticated/reconciliacao'
      path: '/reconciliacao'
      fullPath: '/reconciliacao'
      preLoaderRoute: typeof AuthenticatedReconciliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordens-servico': {
      id: '/_authenticated/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AuthenticatedOrdensServicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/licencas': {
      id: '/_authenticated/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AuthenticatedLicencasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/centros-custo': {
      id: '/_authenticated/centros-custo'
      path: '/centros-custo'
      fullPath: '/centros-custo'
      preLoaderRoute: typeof AuthenticatedCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos': {
      id: '/_authenticated/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AuthenticatedAtivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alocacoes': {
      id: '/_authenticated/alocacoes'
      path: '/alocacoes'
      fullPath: '/alocacoes'
      preLoaderRoute: typeof AuthenticatedAlocacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/403': {
      id: '/_authenticated/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Authenticated403RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos_/$id': {
      id: '/_authenticated/servicos_/$id'
      path: '/servicos/$id'
      fullPath: '/servicos/$id'
      preLoaderRoute: typeof AuthenticatedServicosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordens-servico_/$id': {
      id: '/_authenticated/ordens-servico_/$id'
      path: '/ordens-servico/$id'
      fullPath: '/ordens-servico/$id'
      preLoaderRoute: typeof AuthenticatedOrdensServicoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes_/$id': {
      id: '/_authenticated/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos_/$id': {
      id: '/_authenticated/ativos_/$id'
      path: '/ativos/$id'
      fullPath: '/ativos/$id'
      preLoaderRoute: typeof AuthenticatedAtivosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auditoria_/$tabela/$id': {
      id: '/_authenticated/auditoria_/$tabela/$id'
      path: '/auditoria/$tabela/$id'
      fullPath: '/auditoria/$tabela/$id'
      preLoaderRoute: typeof AuthenticatedAuditoriaTabelaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  Authenticated403Route: typeof Authenticated403Route
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAlocacoesRoute: typeof AuthenticatedAlocacoesRoute
  AuthenticatedAtivosRoute: typeof AuthenticatedAtivosRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCentrosCustoRoute: typeof AuthenticatedCentrosCustoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedLicencasRoute: typeof AuthenticatedLicencasRoute
  AuthenticatedOrdensServicoRoute: typeof AuthenticatedOrdensServicoRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedReconciliacaoRoute: typeof AuthenticatedReconciliacaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRelatoriosOsRoute: typeof AuthenticatedRelatoriosOsRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedAtivosIdRoute: typeof AuthenticatedAtivosIdRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedOrdensServicoIdRoute: typeof AuthenticatedOrdensServicoIdRoute
  AuthenticatedServicosIdRoute: typeof AuthenticatedServicosIdRoute
  AuthenticatedAuditoriaTabelaIdRoute: typeof AuthenticatedAuditoriaTabelaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  Authenticated403Route: Authenticated403Route,
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAlocacoesRoute: AuthenticatedAlocacoesRoute,
  AuthenticatedAtivosRoute: AuthenticatedAtivosRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCentrosCustoRoute: AuthenticatedCentrosCustoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedLicencasRoute: AuthenticatedLicencasRoute,
  AuthenticatedOrdensServicoRoute: AuthenticatedOrdensServicoRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedReconciliacaoRoute: AuthenticatedReconciliacaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRelatoriosOsRoute: AuthenticatedRelatoriosOsRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedAtivosIdRoute: AuthenticatedAtivosIdRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedOrdensServicoIdRoute: AuthenticatedOrdensServicoIdRoute,
  AuthenticatedServicosIdRoute: AuthenticatedServicosIdRoute,
  AuthenticatedAuditoriaTabelaIdRoute: AuthenticatedAuditoriaTabelaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConcluirRoute: typeof AuthConcluirRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConcluirRoute: AuthConcluirRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CadastroRoute: CadastroRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
